// <auto-generated />
using System;
using CMS.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CMS.Infrastructure.Migrations
{
    [DbContext(typeof(CMSDbContext))]
    [Migration("20200316212610_AddFields")]
    partial class AddFields
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CMS.Domain.Models.Cow", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double?>("BoughtPrice")
                        .HasColumnType("float");

                    b.Property<long>("CowshedId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateOfDeath")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateOfSold")
                        .HasColumnType("datetime2");

                    b.Property<string>("EarningNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(10)")
                        .HasMaxLength(10);

                    b.Property<long?>("FatherId")
                        .HasColumnType("bigint");

                    b.Property<short>("Gender")
                        .HasColumnType("smallint");

                    b.Property<bool>("InPregnant")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<long?>("MotherId")
                        .HasColumnType("bigint");

                    b.Property<string>("PassportNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(25)")
                        .HasMaxLength(25);

                    b.Property<string>("PseudoName")
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<double?>("SoldPrice")
                        .HasColumnType("float");

                    b.Property<short>("Status")
                        .HasColumnType("smallint");

                    b.Property<short>("Type")
                        .HasColumnType("smallint");

                    b.Property<double?>("Weight")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("CowshedId");

                    b.HasIndex("FatherId");

                    b.HasIndex("MotherId");

                    b.ToTable("Cows","dbo");
                });

            modelBuilder.Entity("CMS.Domain.Models.CowAggregate.Cowshed", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DateOfBuild")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(25)")
                        .HasMaxLength(25);

                    b.Property<short>("NumberOfPlaces")
                        .HasColumnType("smallint");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("Cowsheds","dbo");
                });

            modelBuilder.Entity("CMS.Domain.Models.CowAggregate.Insemination", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("ByDoctor")
                        .HasColumnType("bit");

                    b.Property<short?>("CowType")
                        .HasColumnType("smallint");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<long?>("FatherId")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<long>("MotherId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("FatherId");

                    b.HasIndex("MotherId");

                    b.ToTable("Inseminations");
                });

            modelBuilder.Entity("CMS.Domain.Models.CowAggregate.Milking", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("AdditionTime")
                        .HasColumnType("datetime2");

                    b.Property<long>("CowId")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<short>("Volume")
                        .HasColumnType("smallint");

                    b.HasKey("Id");

                    b.HasIndex("CowId");

                    b.ToTable("Milkings");
                });

            modelBuilder.Entity("CMS.Domain.Models.CowAggregate.Pregnancy", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long?>("ChildId")
                        .HasColumnType("bigint");

                    b.Property<short>("CowType")
                        .HasColumnType("smallint");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<long?>("InseminationId")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("SuggestedeEndDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ChildId");

                    b.HasIndex("InseminationId")
                        .IsUnique()
                        .HasFilter("[InseminationId] IS NOT NULL");

                    b.ToTable("Pregnancies");
                });

            modelBuilder.Entity("CMS.Domain.Models.Disease", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("CowId")
                        .HasColumnType("bigint");

                    b.Property<string>("Cure")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Start")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Stop")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("SuggestedExpiriedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CowId");

                    b.ToTable("Diseases");
                });

            modelBuilder.Entity("CMS.Domain.Models.Cow", b =>
                {
                    b.HasOne("CMS.Domain.Models.CowAggregate.Cowshed", "Cowshed")
                        .WithMany("Cows")
                        .HasForeignKey("CowshedId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CMS.Domain.Models.Cow", "Father")
                        .WithMany()
                        .HasForeignKey("FatherId");

                    b.HasOne("CMS.Domain.Models.Cow", "Mother")
                        .WithMany()
                        .HasForeignKey("MotherId");
                });

            modelBuilder.Entity("CMS.Domain.Models.CowAggregate.Insemination", b =>
                {
                    b.HasOne("CMS.Domain.Models.Cow", "Father")
                        .WithMany("InseminationsAsFather")
                        .HasForeignKey("FatherId");

                    b.HasOne("CMS.Domain.Models.Cow", "Mother")
                        .WithMany("InseminationsAsMother")
                        .HasForeignKey("MotherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CMS.Domain.Models.CowAggregate.Milking", b =>
                {
                    b.HasOne("CMS.Domain.Models.Cow", "Cow")
                        .WithMany("Milkings")
                        .HasForeignKey("CowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CMS.Domain.Models.CowAggregate.Pregnancy", b =>
                {
                    b.HasOne("CMS.Domain.Models.Cow", "Child")
                        .WithMany("Pregnancies")
                        .HasForeignKey("ChildId");

                    b.HasOne("CMS.Domain.Models.CowAggregate.Insemination", "Insemination")
                        .WithOne("Pregnancy")
                        .HasForeignKey("CMS.Domain.Models.CowAggregate.Pregnancy", "InseminationId");
                });

            modelBuilder.Entity("CMS.Domain.Models.Disease", b =>
                {
                    b.HasOne("CMS.Domain.Models.Cow", "Cow")
                        .WithMany("Diseases")
                        .HasForeignKey("CowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
